# Artificial Neural Networks

## Library Imports

In [1]:
import pandas as pd
import tensorflow as tf 
import numpy as np

In [2]:
tf.__version__

'2.11.0'

## Part 1 Data Pre-processing

In [3]:
dataset = pd.read_csv("Churn_Modelling.csv")
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
# pd.read_csv("https://raw.githubusercontent.com/Sagarkeshave/Fish_Weight_App/main/Fish.csv")

`Row No, Cust ID , Surname wont have empact on learning model so will drop`

In [5]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [6]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [7]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data


Label Encoding the "Gender" column

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X [ : , 2 ] = le.fit_transform(X[:, 2])

In [9]:
print(X)     # Female replaced by 0 and male by 1

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding on "Geography" column

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer( transformers = [("encoder", OneHotEncoder(), [1])], remainder = "passthrough" )
X = np.array(ct.fit_transform(X))

In [11]:
print(X)   # aLL VALUES FILLED

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting Data Set into training and test set

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

### Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing ANN

In [14]:
ann = tf.keras.models.Sequential()

### Adding input layer and first hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

### Adding the 2nd hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

### Adding the output layer

In [17]:
ann.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

## Part 3 - Training the ANN 

### Compiling the ANN

In [18]:
ann.compile(optimizer = "adam" , loss ="binary_crossentropy" , metrics = ["accuracy"]) 

# For binary classification loss = binary_crossentropy and for multi_class loss = categorical_crossentropy

### Training the ANN on training dataset

In [19]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100 )

Epoch 1/100
250/250 [==============================] - 5s 2ms/step - loss: 0.5795 - accuracy: 0.7381
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4691 - accuracy: 0.7979
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4442 - accuracy: 0.8027
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4337 - accuracy: 0.8076
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4266 - accuracy: 0.8116
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4187 - accuracy: 0.8167
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4100 - accuracy: 0.8225
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4012 - accuracy: 0.8266
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3938 - accuracy: 0.8300
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3872 - accura

## Part 4 - Making prediction and evaluating the model

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

In [20]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))

1/1 [==============================] - 0s 213ms/step
[[0.01521285]]


In [21]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 26ms/step
[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

**Note - 3:** As we applied standard scalar tranformation scaling while pre-processing same need to be applied while prediction (Just tranform method not fit_transform)

### Predicting test set results 

In [22]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1506   89]
 [ 188  217]]


0.8615

In [24]:
ann.save("Saved_model/ANN_1")

INFO:tensorflow:Assets written to: Saved_model/ANN_1\assets


INFO:tensorflow:Assets written to: Saved_model/ANN_1\assets


In [25]:
ann.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 6)                 78        
                                                                 
 dense_1 (Dense)             (None, 6)                 42        
                                                                 
 dense_2 (Dense)             (None, 1)                 7         
                                                                 
Total params: 127
Trainable params: 127
Non-trainable params: 0
_________________________________________________________________


In [26]:
my_model = tf.keras.models.load_model("Saved_model/ANN_1")


In [27]:
my_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 6)                 78        
                                                                 
 dense_1 (Dense)             (None, 6)                 42        
                                                                 
 dense_2 (Dense)             (None, 1)                 7         
                                                                 
Total params: 127
Trainable params: 127
Non-trainable params: 0
_________________________________________________________________
